artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: logs
  TENSORBOARD_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data
  EVALUATION_DIR: evaluation

source_data:
      - ../data/cat
      - ../data/dog

local_data:
  - data/dog
  - data/cat

mlflow_config:
  ARTIFACTS_DIR: artifacts
  EXPERIMENT_NAME: Road_Detection
  RUN_NAME: experimentation2
  REMOTE_SERVER_URI: http://0.0.0.0:5000

  